-- Généré par scripts/gen-zones-sql.ts depuis src/lib/zones.ts : ne pas modifier à la main.
insert into public.zones (code, nom, type, region) values
  ('01', 'Ain', 'departement', 'Auvergne-Rhône-Alpes'),
  ('02', 'Aisne', 'departement', 'Hauts-de-France'),
  ('03', 'Allier', 'departement', 'Auvergne-Rhône-Alpes'),
  ('04', 'Alpes-de-Haute-Provence', 'departement', 'Provence-Alpes-Côte d''Azur'),
  ('05', 'Hautes-Alpes', 'departement', 'Provence-Alpes-Côte d''Azur'),
  ('06', 'Alpes-Maritimes', 'departement', 'Provence-Alpes-Côte d''Azur'),
  ('07', 'Ardèche', 'departement', 'Auvergne-Rhône-Alpes'),
  ('08', 'Ardennes', 'departement', 'Grand Est'),
  ('09', 'Ariège', 'departement', 'Occitanie'),
  ('10', 'Aube', 'departement', 'Grand Est'),
  ('11', 'Aude', 'departement', 'Occitanie'),
  ('12', 'Aveyron', 'departement', 'Occitanie'),
  ('13', 'Bouches-du-Rhône', 'departement', 'Provence-Alpes-Côte d''Azur'),
  ('14', 'Calvados', 'departement', 'Normandie'),
  ('15', 'Cantal', 'departement', 'Auvergne-Rhône-Alpes'),
  ('16', 'Charente', 'departement', 'Nouvelle-Aquitaine'),
  ('17', 'Charente-Maritime', 'departement', 'Nouvelle-Aquitaine'),
  ('18', 'Cher', 'departement', 'Centre-Val de Loire'),
  ('19', 'Corrèze', 'departement', 'Nouvelle-Aquitaine'),
  ('2A', 'Corse-du-Sud', 'departement', 'Corse'),
  ('2B', 'Haute-Corse', 'departement', 'Corse'),
  ('21', 'Côte-d''Or', 'departement', 'Bourgogne-Franche-Comté'),
  ('22', 'Côtes-d''Armor', 'departement', 'Bretagne'),
  ('23', 'Creuse', 'departement', 'Nouvelle-Aquitaine'),
  ('24', 'Dordogne', 'departement', 'Nouvelle-Aquitaine'),
  ('25', 'Doubs', 'departement', 'Bourgogne-Franche-Comté'),
  ('26', 'Drôme', 'departement', 'Auvergne-Rhône-Alpes'),
  ('27', 'Eure', 'departement', 'Normandie'),
  ('28', 'Eure-et-Loir', 'departement', 'Centre-Val de Loire'),
  ('29', 'Finistère', 'departement', 'Bretagne'),
  ('30', 'Gard', 'departement', 'Occitanie'),
  ('31', 'Haute-Garonne', 'departement', 'Occitanie'),
  ('32', 'Gers', 'departement', 'Occitanie'),
  ('33', 'Gironde', 'departement', 'Nouvelle-Aquitaine'),
  ('34', 'Hérault', 'departement', 'Occitanie'),
  ('35', 'Ille-et-Vilaine', 'departement', 'Bretagne'),
  ('36', 'Indre', 'departement', 'Centre-Val de Loire'),
  ('37', 'Indre-et-Loire', 'departement', 'Centre-Val de Loire'),
  ('38', 'Isère', 'departement', 'Auvergne-Rhône-Alpes'),
  ('39', 'Jura', 'departement', 'Bourgogne-Franche-Comté'),
  ('40', 'Landes', 'departement', 'Nouvelle-Aquitaine'),
  ('41', 'Loir-et-Cher', 'departement', 'Centre-Val de Loire'),
  ('42', 'Loire', 'departement', 'Auvergne-Rhône-Alpes'),
  ('43', 'Haute-Loire', 'departement', 'Auvergne-Rhône-Alpes'),
  ('44', 'Loire-Atlantique', 'departement', 'Pays de la Loire'),
  ('45', 'Loiret', 'departement', 'Centre-Val de Loire'),
  ('46', 'Lot', 'departement', 'Occitanie'),
  ('47', 'Lot-et-Garonne', 'departement', 'Nouvelle-Aquitaine'),
  ('48', 'Lozère', 'departement', 'Occitanie'),
  ('49', 'Maine-et-Loire', 'departement', 'Pays de la Loire'),
  ('50', 'Manche', 'departement', 'Normandie'),
  ('51', 'Marne', 'departement', 'Grand Est'),
  ('52', 'Haute-Marne', 'departement', 'Grand Est'),
  ('53', 'Mayenne', 'departement', 'Pays de la Loire'),
  ('54', 'Meurthe-et-Moselle', 'departement', 'Grand Est'),
  ('55', 'Meuse', 'departement', 'Grand Est'),
  ('56', 'Morbihan', 'departement', 'Bretagne'),
  ('57', 'Moselle', 'departement', 'Grand Est'),
  ('58', 'Nièvre', 'departement', 'Bourgogne-Franche-Comté'),
  ('59', 'Nord', 'departement', 'Hauts-de-France'),
  ('60', 'Oise', 'departement', 'Hauts-de-France'),
  ('61', 'Orne', 'departement', 'Normandie'),
  ('62', 'Pas-de-Calais', 'departement', 'Hauts-de-France'),
  ('63', 'Puy-de-Dôme', 'departement', 'Auvergne-Rhône-Alpes'),
  ('64', 'Pyrénées-Atlantiques', 'departement', 'Nouvelle-Aquitaine'),
  ('65', 'Hautes-Pyrénées', 'departement', 'Occitanie'),
  ('66', 'Pyrénées-Orientales', 'departement', 'Occitanie'),
  ('67', 'Bas-Rhin', 'departement', 'Grand Est'),
  ('68', 'Haut-Rhin', 'departement', 'Grand Est'),
  ('69', 'Rhône', 'departement', 'Auvergne-Rhône-Alpes'),
  ('70', 'Haute-Saône', 'departement', 'Bourgogne-Franche-Comté'),
  ('71', 'Saône-et-Loire', 'departement', 'Bourgogne-Franche-Comté'),
  ('72', 'Sarthe', 'departement', 'Pays de la Loire'),
  ('73', 'Savoie', 'departement', 'Auvergne-Rhône-Alpes'),
  ('74', 'Haute-Savoie', 'departement', 'Auvergne-Rhône-Alpes'),
  ('75', 'Paris', 'departement', 'Île-de-France'),
  ('75-1', 'Paris 1er – Louvre', 'arrondissement', 'Île-de-France'),
  ('75-2', 'Paris 2e – Bourse', 'arrondissement', 'Île-de-France'),
  ('75-3', 'Paris 3e – Temple', 'arrondissement', 'Île-de-France'),
  ('75-4', 'Paris 4e – Hôtel-de-Ville', 'arrondissement', 'Île-de-France'),
  ('75-5', 'Paris 5e – Panthéon', 'arrondissement', 'Île-de-France'),
  ('75-6', 'Paris 6e – Luxembourg', 'arrondissement', 'Île-de-France'),
  ('75-7', 'Paris 7e – Palais-Bourbon', 'arrondissement', 'Île-de-France'),
  ('75-8', 'Paris 8e – Élysée', 'arrondissement', 'Île-de-France'),
  ('75-9', 'Paris 9e – Opéra', 'arrondissement', 'Île-de-France'),
  ('75-10', 'Paris 10e – Entrepôt', 'arrondissement', 'Île-de-France'),
  ('75-11', 'Paris 11e – Popincourt', 'arrondissement', 'Île-de-France'),
  ('75-12', 'Paris 12e – Reuilly', 'arrondissement', 'Île-de-France'),
  ('75-13', 'Paris 13e – Gobelins', 'arrondissement', 'Île-de-France'),
  ('75-14', 'Paris 14e – Observatoire', 'arrondissement', 'Île-de-France'),
  ('75-15', 'Paris 15e – Vaugirard', 'arrondissement', 'Île-de-France'),
  ('75-16', 'Paris 16e – Passy', 'arrondissement', 'Île-de-France'),
  ('75-17', 'Paris 17e – Batignolles-Monceau', 'arrondissement', 'Île-de-France'),
  ('75-18', 'Paris 18e – Buttes-Montmartre', 'arrondissement', 'Île-de-France'),
  ('75-19', 'Paris 19e – Buttes-Chaumont', 'arrondissement', 'Île-de-France'),
  ('75-20', 'Paris 20e – Ménilmontant', 'arrondissement', 'Île-de-France'),
  ('76', 'Seine-Maritime', 'departement', 'Normandie'),
  ('77', 'Seine-et-Marne', 'departement', 'Île-de-France'),
  ('78', 'Yvelines', 'departement', 'Île-de-France'),
  ('79', 'Deux-Sèvres', 'departement', 'Nouvelle-Aquitaine'),
  ('80', 'Somme', 'departement', 'Hauts-de-France'),
  ('81', 'Tarn', 'departement', 'Occitanie'),
  ('82', 'Tarn-et-Garonne', 'departement', 'Occitanie'),
  ('83', 'Var', 'departement', 'Provence-Alpes-Côte d''Azur'),
  ('84', 'Vaucluse', 'departement', 'Provence-Alpes-Côte d''Azur'),
  ('85', 'Vendée', 'departement', 'Pays de la Loire'),
  ('86', 'Vienne', 'departement', 'Nouvelle-Aquitaine'),
  ('87', 'Haute-Vienne', 'departement', 'Nouvelle-Aquitaine'),
  ('88', 'Vosges', 'departement', 'Grand Est'),
  ('89', 'Yonne', 'departement', 'Bourgogne-Franche-Comté'),
  ('90', 'Territoire de Belfort', 'departement', 'Bourgogne-Franche-Comté'),
  ('91', 'Essonne', 'departement', 'Île-de-France'),
  ('92', 'Hauts-de-Seine', 'departement', 'Île-de-France'),
  ('93', 'Seine-Saint-Denis', 'departement', 'Île-de-France'),
  ('94', 'Val-de-Marne', 'departement', 'Île-de-France'),
  ('95', 'Val-d''Oise', 'departement', 'Île-de-France'),
  ('971', 'Guadeloupe', 'drom', 'Guadeloupe'),
  ('972', 'Martinique', 'drom', 'Martinique'),
  ('973', 'Guyane', 'drom', 'Guyane'),
  ('974', 'La Réunion', 'drom', 'La Réunion'),
  ('976', 'Mayotte', 'drom', 'Mayotte'),
  ('98', 'Monaco', 'monaco', 'Monaco')
on conflict (code) do update set nom = excluded.nom, type = excluded.type, region = excluded.region;
